application:
  security:
    admin:
      username: ${ADMIN_USERNAME:admin@default.com}
      password: ${ADMIN_PASSWORD:defaultpassword}
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 3600000
spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/cheap_market
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


